# The URL the site will be built for

# this variable has to be set but it is not used
# inside the templates (end in '/')
base_url = "https://earl-workshop.github.io/"

# When adapting the title, do not forget to also adjust base_url above
title = "EARL Workshop"
description = ""

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "cheerfully-light"

# Whether external links are to be opened in a new tab
external_links_target_blank = true

[extra]

navigation = [
    { name = "About", target = "" },
    { name = "Workshop Activities", target = "activities/" },
    { name = "Call for Papers", target = "join/" },
    { name = "Organizers", target = "questions/" },
    { name = "PC Members", target = "requirements/" },
    { name = "Sponsors", target = "certificates/" },
    { name = "Contact", target = "code-of-conduct/" },
]

twitter_image = "https://raw.githubusercontent.com/coderefinery/coderefinery-artwork/main/socialshare/socialshare-workshop.png"

# plausible.io analytics
plausible = { src = "https://plausible.cs.aalto.fi/js/script.js", domain = "coderefinery.github.io", github_ref = "refs/heads/main" }


# you can place multiple logos like this
# the image file(s) need to be placed in content/logos
logos = [
#   { alt_text = "CodeRefinery logo", target_url = "https://coderefinery.org/", image = "coderefinery.png" },
    { alt_text = "EARL Workshop LOGO", target_url = "https://earl-workshop.github.io/", image = "EARL_logo.png" }
]

# adapt this
registration_link = "https://easychair.org/my/conference?conf=recsys2024workshops"
source_repo = "https://github.com/earl-workshop/earl-workshop.github.io"
how_to_join_video = "https://youtu.be/QUAZELOioUY"

# uncomment as soon as registration opens
registration_is_open = true

# uncomment as soon as registration closes
# registration_is_closed = true
